### ISSUE TITLE
Default `spin new go` project fails to run

### ISSUE THREAD

**Issue by pannous** [fermyon/spin#886] opened 2022-11-08 09:45 UTC
trying to run an unmodified `spin new go` project 

on MacOS 13.0 

```
-rw-r--r--  1 me  staff     277 Nov  8 10:36 main.go
-rw-r--r--  1 me  staff     345 Nov  8 10:36 spin.toml
-rw-r--r--  1 me  staff     160 Nov  8 10:38 go.mod
-rw-r--r--  1 me  staff     406 Nov  8 10:38 go.sum
-rwxr-xr-x  1 me  staff  217447 Nov  8 10:38 main.wasm
```

```
> spin build
Executing the build command for component hi: tinygo build -wasm-abi=generic -target=wasi -gc=leaking -no-debug -o main.wasm main.go
Successfully ran the build command for the Spin components.

> spin up
Serving http://127.0.0.1:3000
Available Routes:
  hi: http://127.0.0.1:3000 (wildcard)

2022-11-08T09:39:43.558692Z ERROR spin_http: Error processing request: wasm trap: wasm `unreachable` instruction executed
wasm backtrace:
    0: 0x3aa4 - <unknown>!runtime.runtimePanic
```

upon opening http://127.0.0.1:3000

**Comment by vdice** [comment] 2023-02-15 21:33
As mentioned [above](https://github.com/fermyon/spin/issues/886#issuecomment-1306939283), this appears to be a duplicate of https://github.com/fermyon/spin/issues/820 (assuming use of TinyGo 0.26.0).  Closing.

**Closed by vdice** 2023-02-15 21:33 UTC
Labels: bug
