### ISSUE TITLE
Hidden cli flags on `spin up`

### ISSUE THREAD

**Issue by adamreese** [fermyon/spin#1078] opened 2023-01-27 20:47 UTC
Some cli flags are not displayed for `spin up --help`.  For example `--log-dir`, `--follow`, and `--follow-all`.  

I believe they're trigger specific but should there be a standard for logging or  a way to view available flags without `spin trigger http --help`?

**Comment by rajatjindal** [comment] 2023-01-28 17:13
possibly duplicate of https://github.com/fermyon/spin/issues/993 and https://github.com/fermyon/spin/issues/928

**Comment by itowlson** [comment] 2023-01-29 19:49
They are displayed if there is a `spin.toml` present: https://github.com/fermyon/spin/issues/815

I agree the common ones should be surfaced on `spin up` regardless.

**Closed** 2023-01-30 20:26 UTC
Labels: area/CLI
