### ISSUE TITLE
Add twitter card to spin documentation

### ISSUE THREAD

**Issue by tpmccallum** [fermyon/spin#686] opened 2022-08-12 03:55 UTC
A user Tweeted about trying Spin via the official docs. Image in the Tweet seems generic and it would be awesome to see a Spin logo etc. in their Tweet.

Here is what the Tweet currently shows.

<img width="611" alt="Screen Shot 2022-08-12 at 1 51 16 pm" src="https://user-images.githubusercontent.com/9831342/184282244-a3b5f533-7cff-4d50-9558-b469d4091f31.png">

**Comment by kate-goldenring** [comment] 2022-08-17 05:13
ref https://github.com/fermyon/spin/issues/373

**Comment by radu-matei** [comment] 2022-08-18 03:12
This is a duplicate of #373, closing.

Thanks!

**Closed by radu-matei** 2022-08-18 03:12 UTC
Labels: documentation
