### ISSUE TITLE
`spin up` returns an error with a trivial Grain module that works on Wasmtime

### ISSUE THREAD

**Issue by technosophos** [fermyon/spin#631] opened 2022-07-12 23:09 UTC
With the latest version of Grain, I get a Spin error with even the most trivial programs. (wasmtime works fine)

```console
$ grain --version            
0.5.2
```

`main.gr`:
```grain
print("content-type: text/plain")
print("")
print("Hello, World")
```

`spin.toml`:
```toml
spin_version = "1"
authors = ["Matt Butcher <matt.butcher@fermyon.com>"]
description = "Test Grain"
name = "mygrain"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "mygrain"
source = "main.wasm"
[component.trigger]
route = "/..."
executor = { type = "wagi" }
[component.build]
command = "grain compile -o main.wasm main.gr"
```

Wasmtime:
```console
$ wasmtime main.wasm
content-type: text/plain

Hello, World
```

Spin:

```console
$ spin up   
Error: Cannot create module for component mygrain from file /Users/technosophos/Code/Swift/test-spin-template/mygrain/main.wasm

Caused by:
    0: failed to parse WebAssembly module
    1: Invalid input WebAssembly code at offset 327: duplicate import name `wasi_snapshot_preview1::fd_write` already defined
Error: exit status: 1
```

**Comment by technosophos** [comment] 2022-07-12 23:18
Incidentally, using the `--release` flag on the Grain compiler seems to have fixed this issue. I am guessing that this may have to do with de-duplicating imports

**Comment by etehtsea** [comment] 2022-09-22 10:19
I couldn't reproduce it using (with and w/o `--release` flag)

spin 0.5.0 (1ce374a 2022-09-20)
grain-linux-x64 0.5.3

**Comment by itowlson** [comment] 2022-09-22 20:03
Thanks @etehtsea - tried it here too, and I can't reproduce it either.  @technosophos I'm going to close this for now, but do reopen if you see it again!

**Closed by itowlson** 2022-09-22 20:03 UTC
