### ISSUE TITLE
Error running spin on Ubuntu 22.04

### ISSUE THREAD

**Issue by scotty-c** [fermyon/spin#539] opened 2022-06-07 01:50 UTC
I found this issue running spin on my laptop once I updated to Ubuntu 22.04. It seems like there is an issue with loading the shared Openssl shared libraries with openssl3 package. I installed the packages in the readme `build-essential libssl-dev pkg-config`  downloaded the latest stable version of spin `0.2.0` and got the following error `./spin: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

I was able to get spin working by adding the package from the impish repos 
```
echo "deb http://security.ubuntu.com/ubuntu impish-security main" | sudo tee /etc/apt/sources.list.d/impish-security.list
sudo apt-get update 
sudo apt-get install libssl1.1
```

I thought I would report this as others might be having the same issue on Ubuntu 22.04

**Comment by dicej** [comment] 2022-06-09 15:51
@scotty-c I believe this has been addressed.  When you have a moment, would you please try [the latest canary release](https://github.com/fermyon/spin/releases/tag/canary)?  You'll probably want to `sudo apt-get remove --purge libssl1.1` first to make it a valid test.

**Comment by bacongobbler** [comment] 2022-06-09 19:21
This appears to be a duplicate of #498. I tested the latest canary and it appears to work fine now.

```
><> cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

```
><> spin --version
spin 0.2.0 (1cc8af7 2022-06-09)
```

This can be closed. Thanks @dicej!

**Closed** 2022-06-09 19:23 UTC
