### ISSUE TITLE
Support exclusions in spin watch configuration

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/spin#1692] opened 2023-08-14 19:46 UTC
In some circumstances, it might be nice to be able to "include everything, but" for the Spin watch configuration. Rather than having to explicitly include everything.

In this example: https://github.com/mikkelhegn/docusaurus-example (generated from a standard Docusaurus template), the build output is a subfolder to the `my-websites` folder, where all the source is. Which means if the whole directory is watched, it will loop at every build. To avoid the spin watch config would have to include all subdirectories and files in the root, for it to work well.

In this example, being able to tell Spin to watch everything but the `build` folder, would be a mush easier config.

**Comment by kate-goldenring** [comment] 2023-08-24 02:34
Similar to the [syntax of `.gitignore`](https://www.atlassian.com/git/tutorials/saving-changes/gitignore), I'd imaging us supporting "!build".

**Comment by kate-goldenring** [comment] 2023-08-24 02:38
Looks like we have [`ignore_patterns` in our watch Config](https://github.com/fermyon/spin/blob/main/src/watch_filter.rs#L209). @calebschoepp do we already have support for ignoring certain paths?

**Comment by calebschoepp** [comment] 2023-08-24 16:38
@kate-goldenring currently the ignored paths are hardcoded and we don't support any way for users to pass in paths that they want to ignore. I do think that supporting some sort of ignore path is a good idea. Perhaps the simplest implementation is just treating watch paths with a `!` prefix as something to be ignored like Kate mentioned.

**Comment by me-diru** [comment] 2024-06-12 23:54
Hi!

The code has gone through some refactor from the time this issue was raised. After some initial testing, I think the existing code implements @kate-goldenring and @calebschoepp suggestion of using `!` in front of the file/folder in watch files.

For example, when I included everything in the file and used `!filename.rs`, it is excluded from spin watch, similarly can exclude a folder with `!src\*`

Would like to know your thoughts on if covers the issue or anything else/edge-cases to look out

![image](https://github.com/fermyon/spin/assets/39561007/a5b0af4f-4b8e-4e76-8306-2eff3f0ac183)

Appreciate your input! :D

**Comment by itowlson** [comment] 2024-06-12 23:58
I think none of your patterns cover `spin.toml` - your wildcard is `*/*` which I would expect to cover subdirectories only.

But `spin.toml` should be watched anyway.  A component shouldn't be able to ignore away manifest changes.

**Comment by itowlson** [comment] 2024-06-13 00:05
I don't see anything checking for `!` patterns unless it's already handled by the `watchexec` glob filter.  But there's a separate checker for `spin.toml` which should be reloading when that file changes regardless of anything in the `build.watch` lists.  I'll try to reproduce - thanks for the heads up.

**Comment by itowlson** [comment] 2024-06-13 00:14
Huh.  Seems like the `!` prefix does work.  I better claim this as an achievement quick.

**Comment by me-diru** [comment] 2024-06-13 00:16
`spin.toml` was a bad example to show my intention, but I am glad it wasn't supposed to happen :D 

In general, it was interesting to see files/folders getting excluded as I could not see anything in the[ existing code explicitly handling this case](https://github.com/fermyon/spin/blob/main/src/commands/watch/filters.rs#L180). Maybe it is already handled by the `watchexec` glob filer like you mentioned.

**Comment by itowlson** [comment] 2024-06-13 00:30
Okay _something_ weird is going on with `spin.toml`.

Also, the magic exclude is actually a problem, because we use a single watcher for globs, meaning the lists get combined.  Consider two components, one of which watches `["utils/*.rs"]` and the other one of which watches `["!utils/useful.rs"]`.  Because we combine the lists, changing `utils/useful.rs` does _not_ trigger a rebuild, even though the first component _does_ care about it.

I guess we will need to split out a watcher per component but man that's going to cause a load of pain for synchronising notifications.

**Comment by itowlson** [comment] 2024-06-13 00:36
The exclamation mark syntax isn't mentioned in the docs for watchexec (https://watchexec.github.io/docs/glob-patterns.html) or the underlying glob library (https://docs.rs/globset/latest/globset/).  And the globset filterer docs have a separate parameter for providing exclusions (https://docs.rs/watchexec-filterer-globset/latest/watchexec_filterer_globset/struct.GlobsetFilterer.html#method.new).  I'm not sure I trust my understanding of what's going on here.

**Comment by itowlson** [comment] 2024-06-13 00:58
`watchexec --filter-file` also allows (undocumented?) for the `!` syntax and passes it unmodified into `GlobsetFilterer` so here we are I guess.

**Comment by itowlson** [comment] 2024-06-13 01:33
Okay the situation with `spin.toml` is a bit more nuanced than it appeared.  We _do_ still monitor for changes in `spin.toml` so that we can reconfigure the watchers on a manifest change.  All that is working as intended.  However, we also implicitly watch `spin.toml` as part of each component's `build` and `artifact` filters, so that we can rebuild/reload if anything interesting happens (e.g. the `build.command` changes or the `files` section changes).  And adding `!spin.toml` overrides that, meaning that changes to `spin.toml` no longer cause a rebuild, making it _look_ like we are no longer responding to manifest changes.  But we are - just not to trigger rebuilds for that component.

I'm not too concerned about this.  Now I understand that it's limited to "this component will no longer rebuild/reload on a spin.toml change," it seems like an edge case where the user gets what they asked for even if they regret asking for it.  Let me know if you feel differently about it.

What I _am_ concerned about is that exclusions on one component override inclusions on other components.  That's a nasty little surprise for anyone who uses the exclusion syntax.

**Comment by calebschoepp** [comment] 2024-06-13 17:41
> Okay the situation with `spin.toml` is a bit more nuanced than it appeared. We _do_ still monitor for changes in `spin.toml` so that we can reconfigure the watchers on a manifest change. All that is working as intended. However, we also implicitly watch `spin.toml` as part of each component's `build` and `artifact` filters, so that we can rebuild/reload if anything interesting happens (e.g. the `build.command` changes or the `files` section changes). And adding `!spin.toml` overrides that, meaning that changes to `spin.toml` no longer cause a rebuild, making it _look_ like we are no longer responding to manifest changes. But we are - just not to trigger rebuilds for that component.
> 
> I'm not too concerned about this. Now I understand that it's limited to "this component will no longer rebuild/reload on a spin.toml change," it seems like an edge case where the user gets what they asked for even if they regret asking for it. Let me know if you feel differently about it.

I think that behaviour is reasonable.

**Comment by itowlson** [comment] 2024-06-13 22:54
@mikkelhegn Please give the latest Spin build a test and let me know if you run into any weirdness with the `!` syntax.  We have not done anything to enable it but seem to be inheriting it from the library we use, but it's not very documented and I am not sure whether to trust it enough to close this issue.  If it's working well for you with the fixes in #2554  then we can close this.

**Comment by itowlson** [comment] 2024-06-25 02:55
okay nobody has shrieked at me about #2554 not working so gonna MASH THAT CLOSE BUTTON

**Closed by itowlson** 2024-06-25 02:55 UTC
Labels: good first issue, area/app-def-and-config
