### ISSUE TITLE
UX: Improve error message when app needs to be built

### ISSUE THREAD

**Issue by vdice** [fermyon/spin#859] opened 2022-10-25 19:00 UTC
When a user attempts to `spin deploy` an application that has not been built, they may be greeted with something like the following:

```
$ spin deploy
Error: Failed to expand 'spin.toml' to a bindle

Caused by:
    0: Failed to convert components to Bindle format
    1: Failed to get parcel id for '/Users/vdice/scratch/myapp/target/wasm32-wasi/release/myapp.wasm'
    2: No such file or directory (os error 2)

Learn more at https://developer.fermyon.com/cloud/faq
```

As of https://github.com/fermyon/spin/pull/855 we are now printing the full (low-level) error message, but this information still doesn't educate the user as to the remedy.  I propose we print a suggestion to `spin build` the application before trying again, either in place of or in addition to the error seen above.

An example flow that produces the aforementioned currently:

```
spin new http-rust myapp
cd myapp
spin login
spin deploy
```

**Comment by raymundovr** [comment] 2022-10-25 19:12
Hi @vdice can I work on this one?

**Comment by vdice** [comment] 2022-10-25 19:25
@raymundovr certainly!  I must admit I haven't yet looked at the code -- but if we can check the error and match it with the type above, I'd think we'd be good to print a user-friendly message around needing to build the application first.  Otherwise, if the error isn't a match, we should print the full/raw error message.

**Comment by raymundovr** [comment] 2022-10-25 19:35
The aforementioned worflow prints a different error for me:
```
; spin deploy
Error: Cannot open file target/wasm32-wasi/release/myapp.wasm

Caused by:
    No such file or directory (os error 2)
```

**Comment by raymundovr** [comment] 2022-10-25 19:37
Seeing the comment from @etehtsea it might be necessary to wait for this confirmation @vdice

**Comment by etehtsea** [comment] 2022-10-25 19:53
> The aforementioned workflow prints a different error for me:
> 
> ```
> ; spin deploy
> Error: Cannot open file target/wasm32-wasi/release/myapp.wasm
> 
> Caused by:
>     No such file or directory (os error 2)
> ```

Is you `spin` binary up-to-date?
I've checked again and my experience seems to be consistent:

```
spin main $ git fetch -p upstream && git rebase upstream/main && cargo build --release && cd examples/http-rust-outbound-http && rm ./**/*.wasm && ../../target/release/spin deploy
Current branch main is up to date.
    Finished release [optimized] target(s) in 0.16s
Error: Failed to expand 'spin.toml' to a bindle

Caused by:
    0: Failed to convert components to Bindle format
    1: Failed to get parcel id for '/home/kis/Projects/fermyon/spin/examples/http-rust-outbound-http/target/wasm32-wasi/release/http_rust_outbound_http.wasm'
    2: No such file or directory (os error 2)

Learn more at https://developer.fermyon.com/cloud/faq
```

**Comment by raymundovr** [comment] 2022-10-25 20:00
@etehtsea yes, it is. That's weird...
```
; git fetch -p origin && git rebase origin/main && cargo build --release && cd examples/http-rust-outbound-http && rm ./**/*.wasm && ../../target/release/spin deploy
From https://github.com/fermyon/spin
 - [deleted]         (none)     -> origin/digest
Current branch main is up to date.
   Compiling spin-cli v0.6.0 (/Users/r/FOSS/spin)
    Finished release [optimized] target(s) in 1m 29s
zsh: no matches found: ./**/*.wasm

; ../../target/release/spin deploy
Error: Cannot open file target/wasm32-wasi/release/http_rust_outbound_http.wasm

Caused by:
    No such file or directory (os error 2)
```

```
; git remote -v
origin  https://github.com/fermyon/spin (fetch)
origin  https://github.com/fermyon/spin (push)
```

**Comment by vdice** [comment] 2022-10-25 21:56
> So it feels like rather than using the anyhow inside it, it would be better to use something like thiserror and return an error like MissingBuildArtifact from it and then handle it with anyhow inside the spin app with a user-friendly message.

Thanks for relaying initial investigation and thoughts @etehtsea.  I'd endorse this approach.

@raymundovr hmmm, I've yet to repro the output shown above.  Perhaps try from a fresh clone or removing the entire `target` sub-dir?  Or can try with the `spin new <example name> <app name>` flow as mentioned in the original description above.

**Comment by raymundovr** [comment] 2022-10-26 05:03
@vdice I've tried already with the binary and just tried again with the build from source without success.

Given my unability to reproduce (very weird) and @etehtsea clarity I have unassigned myself.

**Comment by etehtsea** [comment] 2022-11-02 19:19
I'm working on this one

**Comment by etehtsea** [comment] 2022-11-06 14:59
> The aforementioned workflow prints a different error for me:
> 
> ```
> ; spin deploy
> Error: Cannot open file target/wasm32-wasi/release/myapp.wasm
> 
> Caused by:
>     No such file or directory (os error 2)
> ```

Accidentally, I reproduced this one. It was happening before 2871413eb1ccf14d69aa08b532f0445b9e4f3f6b landed to master.

**Comment by etehtsea** [comment] 2022-11-07 09:16
> The aforementioned workflow prints a different error for me:
> 
> ```
> ; spin deploy
> Error: Cannot open file target/wasm32-wasi/release/myapp.wasm
> 
> Caused by:
>     No such file or directory (os error 2)
> ```

I've figured it out. It depends on the config you use. If spin is configured with a bindle server and not the cloud, it fails inside `compute_buildinfo` with the error above.

**Closed** 2022-11-17 06:23 UTC
Labels: good first issue, cli
