### ISSUE TITLE
Install Spin - Error

### ISSUE THREAD

**Issue by tpmccallum** [fermyon/spin#1531] opened 2023-05-22 04:13 UTC
Hi
Just noticing an issue when using the docs installation procedure.

```bash
$ git clone https://github.com/fermyon/spin -b v1.2.1
$ cd spin
$ rustup target add wasm32-wasi
$ rustup target add wasm32-unknown-unknown
$ cargo install --locked --path .
$ spin --help

error: failed to run custom build command for `spin-cli v1.2.0 (/Users/tpmccallum/spin)`

Caused by:
  process didn't exit successfully: `/Users/tpmccallum/spin/target/release/build/spin-cli-1019c0ea55ff8bd4/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'failed to extract build information: the 'year' component could not be parsed

  Caused by:
      the 'year' component could not be parsed', build.rs:28:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `spin-cli v1.2.0 (/Users/tpmccallum/spin)`, intermediate artifacts can be found at `/Users/tpmccallum/spin/target`
```
Looks like `failed to extract build information` error.

**Comment by tpmccallum** [comment] 2023-05-22 04:22
Just tried patch version and it is the same for `1.2.1`

```bash
error: failed to run custom build command for `spin-cli v1.2.1 (/Users/tpmccallum/spin)`

Caused by:
  process didn't exit successfully: `/Users/tpmccallum/spin/target/release/build/spin-cli-e3f453ff94645a94/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'failed to extract build information: the 'year' component could not be parsed

  Caused by:
      the 'year' component could not be parsed', build.rs:28:10

```

**Comment by itowlson** [comment] 2023-05-22 04:27
@cardoso Could this be related to the vergen changes?  (I know I said they didn't make it into 1.2.0 but apparently they did.)  The error appears to be on the `EmitBuilder::emit().expect()` line but I'm not sure why @tpmccallum is hitting it - I just tried a clean checkout and all good.

**Comment by tpmccallum** [comment] 2023-05-22 04:28
This is the `RUST_BACKTRACE=full` version

```
  Caused by:
      the 'year' component could not be parsed', build.rs:28:10
  stack backtrace:
     0:        0x103b72416 - std::backtrace_rs::backtrace::libunwind::trace::h863be41b53c4f884
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:        0x103b72416 - std::backtrace_rs::backtrace::trace_unsynchronized::ha57069b30dcbe3f5
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:        0x103b72416 - std::sys_common::backtrace::_print_fmt::h7dbf0829c4d9fd22
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:65:5
     3:        0x103b72416 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he84dde8223670de4
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:44:22
     4:        0x103b8daaa - core::fmt::write::h0721d4325d1d86bb
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/fmt/mod.rs:1232:17
     5:        0x103b6fa0c - std::io::Write::write_fmt::hf4d04b4d333539fa
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/io/mod.rs:1684:15
     6:        0x103b721fa - std::sys_common::backtrace::_print::h15efcfdd13c9c026
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:47:5
     7:        0x103b721fa - std::sys_common::backtrace::print::hed06273df3ccacbe
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:34:9
     8:        0x103b73963 - std::panicking::default_hook::{{closure}}::he8c58e8d0abf03c5
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:271:22
     9:        0x103b736b8 - std::panicking::default_hook::h8320561bf55c0290
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:290:9
    10:        0x103b73f4b - std::panicking::rust_panic_with_hook::h38dc40cfa47552ba
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:692:13
    11:        0x103b73e64 - std::panicking::begin_panic_handler::{{closure}}::h727c67dc750b5cee
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:583:13
    12:        0x103b72859 - std::sys_common::backtrace::__rust_end_short_backtrace::h6848121e0bfe63be
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:150:18
    13:        0x103b73b2d - rust_begin_unwind
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
    14:        0x103b98203 - core::panicking::panic_fmt::h690b01655a033c26
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
    15:        0x103b98625 - core::result::unwrap_failed::h318e014235203f60
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/result.rs:1750:5
    16:        0x103ad834b - core::result::Result<T,E>::expect::hf9bed4f3819ea38e
    17:        0x103ad60c3 - build_script_build::main::h735172927a7c5ad6
    18:        0x103ad363a - core::ops::function::FnOnce::call_once::h86fd3738a686f6ee
    19:        0x103ad3bad - std::sys_common::backtrace::__rust_begin_short_backtrace::h43ed9a7698a7e2bf
    20:        0x103ad4a40 - std::rt::lang_start::{{closure}}::h7549f360b0843565
    21:        0x103b6ba90 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hb633d246db9c8b3f
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:287:13
    22:        0x103b6ba90 - std::panicking::try::do_call::hcc14a5a158bf6961
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:487:40
    23:        0x103b6ba90 - std::panicking::try::ha053de4a5d927432
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:451:19
    24:        0x103b6ba90 - std::panic::catch_unwind::hdc9235c152d51b66
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panic.rs:140:14
    25:        0x103b6ba90 - std::rt::lang_start_internal::{{closure}}::h77107745b5529819
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:148:48
    26:        0x103b6ba90 - std::panicking::try::do_call::h9edf685df72863ef
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:487:40
    27:        0x103b6ba90 - std::panicking::try::h2dfb970c45e23c24
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:451:19
    28:        0x103b6ba90 - std::panic::catch_unwind::hc60a4924b5d35df8
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panic.rs:140:14
    29:        0x103b6ba90 - std::rt::lang_start_internal::h733b9f59d292f4af
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:148:20
    30:        0x103ad4a18 - std::rt::lang_start::hfe488696256b6890
    31:        0x103ad74b8 - _main
    32:     0x7ff80149841f - <unknown>
```

**Comment by rylev** [comment] 2023-05-22 08:16
I also cannot reproduce this, but it looks like it's might be [this call](https://github.com/rustyhorde/vergen/blob/0d14835fbc1bcf7bc9dc3a4136569204d9f5814e/vergen/src/feature/git/cmd.rs#L650) that's failing. 

@tpmccallum what does running `git log -1 --pretty=format:'%cI'` produce for you?

**Comment by cardoso** [comment] 2023-05-22 15:42
Also no issues here, but it must be the cli. May be worth using one of the libraries instead to make it consistent across the board.

**Comment by tpmccallum** [comment] 2023-05-22 21:18
Hi @rylev 
The command you provided produces the following for me.
```
tpmccallum@192-168-1-23 spin % git log -1 --pretty=format:'%cI'
gpg: Signature made Sat 20 May 00:35:46 2023 AEST
gpg:                using RSA key 4AEE18F83AFDEB23
gpg: Can't check signature: No public key
2023-05-19T16:35:46+02:00
```

**Comment by itowlson** [comment] 2023-05-22 23:57
@cardoso I think we've resisted using the `git2` library in the past because of SSL library linking issues.  I may be behind the times on this though.  And this is build-time rather than run-time so maybe not an issue.

**Comment by itowlson** [comment] 2023-05-23 00:28
@rylev I checked in with Tim and `git` is dumping the spew as well as the timestamp to stdout.  It looks like https://github.com/rustyhorde/vergen/blob/1ef5c5fc4ca58af32b3b5db5cc3a271a887e9f91/vergen/src/feature/git/cmd.rs#L638 then tries to parse the whole thing as an OffsetDateTime.  Testing `OffsetDateTime::parse` on Tim's text gives `Err(ParseFromDescription(InvalidComponent("year")))` which I think is why the `year` thing pops up.

**Comment by rylev** [comment] 2023-05-23 08:22
I've opened [an issue against `vergen`](https://github.com/rustyhorde/vergen/issues/210) that would hopefully fix this.

**Closed** 2023-05-25 23:50 UTC
