### ISSUE TITLE
Split `spin-trigger` `mod runtime_config` into new `spin-runtime-config` crate

### ISSUE THREAD

**Issue by lann** [fermyon/spin#1373] opened 2023-04-12 14:00 UTC
It would be nice if e.g. `SpinKeyValueStoreOpts` could live next to the code it configures in the `spin-key-value-sqlite` crate, but currently that would cause a circular dependency `spin-key-value-sqlite -> spin-key-value -> spin-trigger -> spin-key-value-sqlite`. Splitting into a separate crate would break the circle.

**Comment by fibonacci1729** [comment] 2023-04-12 14:38
Is this a duplicate of https://github.com/fermyon/spin/issues/1359#issue-1656264417?

**Closed** 2023-04-12 14:39 UTC
